name: Build Image
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  IMAGE_NAME: leptos
  IMAGE_FULL: ghcr.io/${{ github.repository }}
  MAJOR_VERSION: 10
  DEFAULT_TAG: ${{ github.ref_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set date tag
        id: date
        run: |
            echo "DATE_TAG=${DEFAULT_TAG}.$(date -u +%Y%m%d)" >> "$GITHUB_ENV"

      - name: GHCR Login
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for updates
        if: ${{ github.event_name == 'schedule' }}  # Only run if triggered by schedule
        run: |
          upd=0
          podman run --quiet --rm ${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }} dnf check-update || upd=$?

          echo "upd=${upd}" >> "$GITHUB_ENV"
          echo "Exit code from dnf check-update: '${upd}'"

      - name: Build
        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
        run: |
          buildah bud \
            --cap-add=all \
            --security-opt=label=type:container_runtime_t \
            --skip-unused-stages=false \
            --device /dev/fuse \
            --pull=newer \
            --label=org.opencontainers.image.title=${{ env.IMAGE_NAME }} \
            --label=org.opencontainers.image.version=${{ env.MAJOR_VERSION }}.${{ env.DATE_TAG }} \
            -t ${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }}

      - name: Rechunk
        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
        run: |
          export CHUNKAH_CONFIG_STR="$(podman inspect "${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }}")"

          podman run --rm \
            --mount=type=image,src="${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }}",target=/chunkah \
            -e CHUNKAH_CONFIG_STR="$CHUNKAH_CONFIG_STR" \
            quay.io/coreos/chunkah build \
            --prune /sysroot/ --label ostree.commit- --label ostree.final-diffid- \
            --label containers.bootc=1 --compressed --max-layers 128 \
            --tag ${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }} \
          | podman load

      - name: Push
        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
        run: |
          podman push ${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }}

      - name: Add date-specific tag and get digest
        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
        run: |
          IMAGE_DIGEST=$(podman inspect --format '{{.Digest}}' "${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }}")
          echo "IMAGE_DIGEST=$IMAGE_DIGEST" >> $GITHUB_ENV

          podman tag "${{ env.IMAGE_FULL }}:${{ env.DEFAULT_TAG }}" "${{ env.IMAGE_FULL }}:${{ env.DATE_TAG }}"
          podman push "${{ env.IMAGE_FULL }}:${{ env.DATE_TAG }}"

      - name: Install Cosign
        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
        uses: sigstore/cosign-installer@v4.1.2

      - name: Sign image by digest
        if: ${{ github.event_name == 'workflow_dispatch' || env.upd != 0 }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        run: |
          cosign sign --yes --new-bundle-format=false --use-signing-config=false --key env://COSIGN_PRIVATE_KEY \
          "${{ env.IMAGE_FULL }}@$IMAGE_DIGEST"
